base:
  project: Flight_price_predition
  random_state: 369
  target_col: Price


load_data:
  raw_dataset_csv: Data/Training_Data/Training_Batch_Files/
  archive_data: Data/Training_Data/Training_Archive_Bad_Data/
  data_from_db: Data/Training_Data/Training_File_From_DB/
  validated_raw_data: Data/Training_Data/Training_Raw_Files_Validated/

data_base_info:
  database_name: flight_price_prediction
  keyspace_name: flight_price_prediction_keyspace
  table_name: training_files
  secure_connect_bundle: Cassandra_Bundle/secure-connect-flight-price-prediction.zip
  client_id: caqhALHQBBIUIZWptJlnouhX
  auth_provider: 9M86beObXwhCR+_L,FSbYX4ZeF_nJ39.pjmDtn8Za-N3L9P+kJwrDxhP4MPZ_a4hRy3Z2FEnxRCI_5SNIJZPm6eJhAvDFG-7F-ZeqPGiqk-BCy+xOr1mZf043J4boBhS



logs:
  log_dir_training: Logs/Training_Logs
  log_dir_prediction: Logs/Prediction_Logs


schema_files:
  training_schema_json: Schema/schema_training.json
  prediction_schema_json: Schema/schema_prediction.json

transformation_pkl:
  one_hot_encoder: Transformation/onehot_encoder.pkl
  cluster: Transformation/Kmeans_cluster.pkl

estimators:
  ElasticNet:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      alpha: 0.9
      l1_ratio: 0.4
model_dir: Models/Available_Prediction_Models

reports:
  params: Reports/params.json
  scores: Reports/scores.json

